---
version: "3.8"
services:
  account-mongodb:
    image: mongo:4.4
    container_name: account-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27018:27017"
    volumes:
      - account-mongo-data:/data/db
    networks:
      - finova-network
  transaction-mongodb:
    image: mongo:4.4
    container_name: transaction-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27019:27017"
    volumes:
      - transaction-mongo-data:/data/db
    networks:
      - finova-network
  loan-mongodb:
    image: mongo:4.4
    container_name: loan-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27020:27017"
    volumes:
      - loan-mongo-data:/data/db
    networks:
      - finova-network
  savings-goals-mongodb:
    image: mongo:4.4
    container_name: savings-goals-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27021:27017"
    volumes:
      - savings-goals-mongo-data:/data/db
    networks:
      - finova-network
  risk-assessment-mongodb:
    image: mongo:4.4
    container_name: risk-assessment-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27022:27017"
    volumes:
      - risk-assessment-mongo-data:/data/db
    networks:
      - finova-network
  compliance-mongodb:
    image: mongo:4.4
    container_name: compliance-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27023:27017"
    volumes:
      - compliance-mongo-data:/data/db
    networks:
      - finova-network
  notification-mongodb:
    image: mongo:4.4
    container_name: notification-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27024:27017"
    volumes:
      - notification-mongo-data:/data/db
    networks:
      - finova-network
  reporting-mongodb:
    image: mongo:4.4
    container_name: reporting-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantsingularity
      MONGO_INITDB_ROOT_PASSWORD: quantsingularity
    ports:
      - "27025:27017"
    volumes:
      - reporting-mongo-data:/data/db
    networks:
      - finova-network
networks:
  finova-network:
volumes:
  account-mongo-data:
  transaction-mongo-data:
  loan-mongo-data:
  savings-goals-mongo-data:
  risk-assessment-mongo-data:
  compliance-mongo-data:
  notification-mongo-data:
  reporting-mongo-data:
