---
server:
  port: 8001

spring:
  application:
    name: eureka-server
  # Security Configuration for Eureka Server
  # Basic authentication is recommended for Eureka to prevent unauthorized registration
  security:
    user:
      name: ${EUREKA_USERNAME:eureka-user}
      password: ${EUREKA_PASSWORD:eureka-password}
      roles: USER

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8001/eureka/
